<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/default/empty/index.css" />
	<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
	<script type="text/javascript">
		$('#loading', parent.document.body).css({
				display: 'none'
		});
	</script>
</head>
<body>
	
</body>
</html>