<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/default/empty/index.css" />
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">$(document).ready(function(){$('#loading', parent.document.body).css({display: 'none'})});</script>
</body>
</html>