<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/logo.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/default/help/index.css');
	</style>
</head>
<body>
	<div class="logo"></div>
	<div class="caption">Справочная информация</div>
	<div class="docs">
		<ol class="docs-list">
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Opisanie rejtingov.doc" target="_blank">Описание рейтингов</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Chto takoe programma Upravlenie dostizhenijami.doc" target="_blank">Что такое программа «Управление достижениями»</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Pravila provedenija obzornyh vstrech.doc" target="_blank">Правила проведения обзорных встреч</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Pravila zapolnenija lichnyh kartochek.doc" target="_blank">Правила заполнения личных карточек</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Rukovodstvo po rabote s Rolf-Personalom.doc" target="_blank">Руководство по работе с «Рольф-Персоналом»</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/Otvety na voprosy.doc" target="_blank">Ответы на вопросы</a></li>
			<li><a href="<?php echo $this->baseUrl() ?>/docs/FAQ.doc" target="_blank">FAQ по УД</a></li>
			<li><a href="http://rolf-websoft:8090/rolfnew/view_doc.html?mode=learning_proc&course_id=514775511970706391" target="_blank">Электронный курс «РОЛЬФ-ПЕРСОНАЛ, этап Планирование»</a></li>
			<li><a href="http://rolf-websoft:8090/rolfnew/view_doc.html?mode=learning_proc&course_id=5416553128819314954" target="_blank">Электронный курс «РОЛЬФ-ПЕРСОНАЛ, Совместители»</a></li>

		</ol>
	</div>
</body>
</html>