<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/lib/GridBox/gridbox.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/default/employees/index.css');
	</style>
	<script type="text/javascript">
		var BASE_URL = '<?php echo $this->baseUrl() ?>';
		//var msg= '<?php echo $this->postIds ?>';
		//alert(msg);
		
	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/app/default/employees/index.js" type="text/javascript"></script>
</head>
<body onload="init()">

	<?php echo $this->employeesList($this->listEmployees) ?>
	<div class="profile">
		<iframe name="profile" src="<?php echo $this->baseUrl() ?>/default/empty"></iframe>
	</div>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
<script type="text/javascript">
	$('#loading', parent.document.body).css({
			display: 'none'
	});
</script>
</html>