<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/lib/GridBox/gridbox.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/default/employees/index.css" />
</head>
<body onload="init()">
<?php echo $this->employeesList($this->listEmployees, $this->rates) ?>
<div class="profile"><iframe name="profile" src="<?php echo $this->baseUrl() ?>/default/empty"></iframe></div>
<script type="text/javascript">var BASE_URL = '<?php echo $this->baseUrl() ?>';</script>
<script src="<?php echo $this->baseUrl() ?>/js/app/default/employees/index.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">$(document).ready(function(){$('#loading', parent.document.body).css({display: 'none'})});</script>
</body>
</html>