<?php $ROLE_FUNC_MANAGER = 8?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/js/lib/Js/Toolbar/css/default.css" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel/css/default.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/card/achievs/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/lib/jquery-ui-1.8.16.custom.css" />
</head>
<body onload="init();">

	<form name="card" action="<?php echo $this->baseUrl() ?>/card/achievs/save" enctype="multipart/form-data" method="post">
		<fieldset>
			<input name="id" type="hidden" value="<?php echo $this->card->id ?>" />
			<input name="userId" type="hidden" value="<?php echo $this->user->getPersonId() ?>" />
			<input name="person_id" type="hidden" value="<?php echo $this->card->person_id ?>" />
			<input name="status_id" type="hidden" value="<?php echo $this->card->status_id ?>" />

			<input name="approvals[plan_mng_id]" type="hidden" value="<?php echo $this->card->plan_mng_id ?>" />
			<input name="approvals[plan_hmg_id]" type="hidden" value="<?php echo $this->card->plan_hmg_id ?>" />
			<input name="approvals[plan_fnc_id]" type="hidden" value="<?php echo $this->card->plan_fnc_id ?>" />

			<input name="approvals[plan_mng_status]" type="hidden" value="<?php echo $this->card->plan_mng_status ?>" />
			<input name="approvals[plan_emp_status]" type="hidden" value="<?php echo $this->card->plan_emp_status ?>" />
			<input name="approvals[plan_hmg_status]" type="hidden" value="<?php echo $this->card->plan_hmg_status ?>" />
			<input name="approvals[plan_fnc_status]" type="hidden" value="<?php echo $this->card->plan_fnc_status ?>" />

			<input name="approvals[rate_mng_id]" type="hidden" value="<?php echo $this->card->rate_mng_id ?>" />
			<input name="approvals[rate_hmg_id]" type="hidden" value="<?php echo $this->card->rate_hmg_id ?>" />
			<input name="approvals[rate_fnc_id]" type="hidden" value="<?php echo $this->card->rate_fnc_id ?>" />

			<input name="approvals[rate_mng_status]" type="hidden" value="<?php echo $this->card->rate_mng_status ?>" />
			<input name="approvals[rate_emp_status]" type="hidden" value="<?php echo $this->card->rate_emp_status ?>" />
			<input name="approvals[rate_hmg_status]" type="hidden" value="<?php echo $this->card->rate_hmg_status ?>" />
			<input name="approvals[rate_fnc_status]" type="hidden" value="<?php echo $this->card->rate_fnc_status ?>" />
			<input name="tab" type="hidden" value="<?php echo $this->tab?>" />

			<table class="panel">
				<tbody>
					<tr>
						<td class="panel-period">
							<div>
								Период:
								<select name="period" id="period">
									<?php foreach($this->periods as $card_id => $period):?>
										<option value="<?php echo $card_id?>,<?php echo $period['year']?>" label="<?php echo $period['name']?>"<?php echo ($this->card->id == $card_id) ? ' selected="selected"' : ''?>><?php echo $period['name']?></option>
									<?php endforeach;?>
								</select>
								<br><span class="translate_menu">Period:</span>
							</div>

						</td>
						<td class="panel-toolbar" id="toolbarBox"></td>
						<td class="panel-status">
							<div class="panel-status<?php echo $this->status->id ?>">
								<span title="Статус карточки"><?php echo $this->status->name ?></span>
								<?php echo ($this->period_text) ? '<span>'.$this->period_text.'</span>' : NULL?>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
			<?php echo $this->achievsHeader($this->emp) ?>
			<div class="tabs">
				<table class="tabs-items">
					<tbody>
						<tr>
							<td id="tabs-item-tasks" class="tabs-item tabs-item-activated"><div><span class="ru">Бизнес-цели (<?php echo (count($this->tasks) - count($this->personalTasks)) ?>)</span><span class="en" style="left: 23px;">Business objectives</span></div></td>
							<td id="tabs-item-compets" class="tabs-item"><div><span class="ru">Компетенции (<?php echo count($this->competences) ?>)</span><span class="en" style="left: 164px;">Competences</span></div></td>
							<td id="tabs-item-trains" class="tabs-item"><div><span class="ru">План развития (<?php echo count($this->trainings) ?>)</span><span class="en" style="left: 316px;">Development plan</span></div></td>
							<td id="tabs-item-comments" class="tabs-item"><div><span class="ru">Комментарии и согласования</span><span class="en" style="left: 470px;">Comments & approvals</span></div></td>
							<td id="tabs-item-personal" class="tabs-item"><div><span class="ru">Форма сотрудника</span><span class="en" style="left: 696px;">Personal form</span></div></td>
							<?php if($this->statistics):?>
								<td id="tabs-item-statistics" class="tabs-item"><div><span class="ru">Статистика</span><span class="en" style="left: 855px;">Statistics</span></div></td>
							<?php endif;?>
						</tr>
					</tbody>
				</table>
				<div class="tabs-body tabs-body-activated" id="tabs-body-tasks">
					<?php
						echo $this->achievsFormTasks($this->tasks, $this->count_func, $this->ratings, $this->rate_weights, $this->card->rtg_tasks_id, $this->userRole & $ROLE_FUNC_MANAGER, $this->card, $this->card->rtg_func_id)
					?>
				</div>
				<div class="tabs-body" id="tabs-body-compets">
					<?php echo $this->achievsFormCompetences($this->competences, $this->ratings, $this->rate_weights, $this->card->rtg_competens_id) ?>
				</div>
				<div class="tabs-body" id="tabs-body-trains">
					<?php echo $this->achievsFormTrainings($this->trainings,
							$this->trainsGroupsMethods, $this->trainsRespons, $this->months, $this->trainsGroupsMethodsActual) ?>
				</div>
				<div class="tabs-body" id="tabs-body-comments">
					<div class="comments-body">
						<div class="ratings-body">
							<table id="ratings" class="ratings-table">
								<tbody>
									<tr>
										<th>Итоговый рейтинг бизнес-целей:</th>
										<td><?php echo $this->ratings[$this->card->rtg_tasks_id] ?></td>
										<th>Итоговый рейтинг компетенций:</th>
										<td><?php echo $this->ratings[$this->card->rtg_competens_id] ?></td>
										<th class="ratings-field-total">Общий рейтинг:</th>
										<td id="fieldRatingTotal" class="field-rating ratings-field-total">
											<?php echo $this->formSelect('ratings[rtg_total_id]', $this->card->rtg_total_id, null, $this->ratings) ?>
											<div><?php echo $this->ratings[$this->card->rtg_total_id] ?></div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<table id="comments" class="grid-body-table comments-table">
							<tbody>
								<tr><th>Комментарий руководителя - <span class="translate_category_tasks">Manager's comment</span></th></tr>
								<tr>
									<td>
										<textarea name="comments[mng_comment]" readonly><?php echo $this->card->mng_comment ?></textarea>
									</td>
								</tr>
								<!--<tr><?php //if ($this->count_func > 0) echo '<th>Комментарий функционального руководителя - <span class="translate_category_tasks">Functional manager\'s comment</span></th>' ?></tr>
								<tr><?php /*if ($this->count_func > 0) echo '
									<td>
										<textarea name="comments[fnc_comment]" readonly>' . $this->card->fnc_comment . '</textarea>
									</td>'*/?>
								</tr>-->
								<tr><th>Рекомендации по развитию карьеры - <span class="translate_category_tasks">Career Development Recommendations</span></th></tr>
								<tr>
									<td class="comments-field-flags">
										<?php echo $this->achievsCareerFlags($this->card->career_flag_id, $this->careerFlags) ?>
									</td>
								</tr>
								<tr>
									<td>
										<textarea name="comments[career_recom]" readonly><?php echo $this->card->career_recom ?></textarea>
									</td>
								</tr>
								<tr><th>Карьерные ожидания сотрудника - <span class="translate_category_tasks">Employee’s Career Expectations</span></th></tr>
								<tr>
									<td>
										<textarea name="comments[career_wait]" readonly><?php echo $this->card->career_wait ?></textarea>
									</td>
								</tr>
								<!--<tr><th>Комментарий сотрудника - <span class="translate_category_tasks">Employee comment</span></th></tr>
								<tr>
									<td>
										<textarea name="comments123[emp_comment]" readonly><?php //echo $this->card->emp_comment ?></textarea>
									</td>
								</tr>-->
							</tbody>
						</table>
						<table class="approvals">
							<tbody>
								<tr>
									<td class="approvals-margin">&nbsp;</td>
									<td><?php echo $this->achievsTableApprovals($this->approvals, $this->card->status_id, $this->count_func) ?></td>
									<td class="approvals-margin">&nbsp;</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="tabs-body" id="tabs-body-personal">
					<div>
					<?php echo $this->achievsFormPersonal(
						$this->tasks,
						$this->personalTrainings,
						$this->personalCompetences,
						$this->ratings,
						$this->rate_weights,
						$this->userRole & $ROLE_FUNC_MANAGER,
						$this->card,
						$this->status->id,
						// данные для компетенций
						$this->competences
						// $this->ratings, $this->rate_weights, $this->card->rtg_competens_id, TRUE
						);?>
					</div>
				</div>
<?php if($this->statistics):?>
				<div class="tabs-body" id="tabs-body-statistics">
					<div>
						<table id="statistics-table">
							<tr>
								<th>Период:</th>
								<th>Рейтинги:</th>
							</tr>
					<?php foreach($this->statistics as $rating):?>
							<tr>
								<td<?php echo ($rating['is_blocked']) ? ' class="crossed" title="Карточка заблокирована"' : NULL?>><div><?php echo $rating['period']['start']?> - <?php echo $rating['period']['end']?></div></td>
								<td<?php echo ($rating['is_blocked']) ? ' class="crossed" title="Карточка заблокирована"' : NULL?>>
									<div class="inline">Итоговый рейтинг бизнес-целей: <span><?php echo ($rating['ratings']['tasks']['name']) ? $rating['ratings']['tasks']['name'] : '-'?></span></div>
									<div class="inline">Итоговый рейтинг компетенций: <span><?php echo ($rating['ratings']['competens']['name']) ? $rating['ratings']['competens']['name'] : '-'?></span></div>
									<div class="inline">Общий рейтинг: <span><?php echo ($rating['ratings']['total']['name']) ? $rating['ratings']['total']['name'] : '-'?></span></div>
								</td>
							</tr>
					<?php endforeach;?>
						</table>
						<div id="statistics-total-rating">Общий итоговый рейтинг: <span><?php echo $this->rate_calc['name']?></span></div>
						<div id="statistics-total-rating-confirmation">Согласование: <span><?php echo ($this->common_rating_confirmed) ? 'Согласовано' : 'Не согласовано'?></span></div>
						<script type="text/javascript">
							var common_rating  = {
								'id'          : <?php echo ($this->common_rating_id) ? $this->common_rating_id : 'null'?>,
								'person_id'   : <?php echo $this->card->person_id ?>,
								'period_year' : <?php echo $this->card->period?>,
								'rating_id'   : <?php echo $this->rate_calc['id']?>
							};
						</script>
						<?php if($this->rate_calc['name'] != 'нет' AND $this->common_rating_confirmed == FALSE AND $this->userRole == 1):?>
						<div id="common_rating_confirmation_buttons">
							<div class="conf_button" value="1">
								<img src='<?php echo $this->baseUrl() ?>/img/achievs/card/toolbar/approval.gif' alt=""/>
								<div>Согласовать<span>Confirm</span></div>
							</div>
&nbsp;
							<div class="conf_button" id="<?php echo $this->common_rating_id?>" value="0">
								<img src='<?php echo $this->baseUrl() ?>/img/achievs/card/toolbar/reject.gif' alt=""/>
								<div>Отклонить<span>Reject</span></div>
							</div>
						</div>
						<?php endif;?>
					</div>
				</div>
<?php endif;?>
			</div>
		</fieldset>
	</form>
<script type="text/javascript">
	var changes = false;
	window.onbeforeunload = function(evt) {
		evt = evt || window.event;
		if(changes == true){
			var error_text = "Вы не сохранили изменения в карточке сотрудника. Закрытие окна может вызвать потерю имеющихся изменений. \n \n"
							+ "You haven't saved changes made in the employee card. Closing the window may cause loss of existing changes.";
			evt.returnValue = error_text;
		}
	}

	var BASE_URL          = '<?php echo $this->baseUrl() ?>';
	var ROLE_VIEWER       = 0;
	var ROLE_EMPLOYEE     = 1;
	var ROLE_MANAGER      = 2;
	var ROLE_HIGH_MANAGER = 4;
	var ROLE_FUNC_MANAGER = 8;
	var ROLE_VIEWER_USER  = <?php echo (!empty($this->user_viewed_posts)) ? '1000' : '9'?>;
	var USER_ROLE         = <?php echo $this->userRole ?>;
	var count_func 		  = <?php echo $this->count_func ?>;
	var emails            = '<?php echo $this->emails ?>';
	var Str_Rate = '<?php
		$rat = array();
		$rates = $this->rate_name_weights;
		foreach ($rates as $key=>$value)
			$rat[] = $key;
		echo implode("," , $rat);
	?>';
	var Rate_Names = Str_Rate.split(",");
	var Str_Weight = '<?php
		$rat = array();
		$rates = $this->rate_name_weights;
		foreach ($rates as $key=>$value)
			$rat[] = $value['weight'];
		echo implode("," , $rat);
	?>';
	var Rate_Weights       = Str_Weight.split(",");
	var previous_bad_rates = '<?php echo $this->previous_bad_rates?>';
	var active_tab         = '<?php echo $this->tab?>';
	var has_statistics     = <?php echo ($this->statistics) ? 'true' : 'false'?>;
	var card_id            = <?php echo $this->card->id?>;
	var is_blocked         = <?php echo ($this->card->is_blocked) ? 'true' : 'false'?>;
</script>
<script src="<?php echo $this->baseUrl() ?>/json/user" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.ui.datepicker-ru.js" type="text/javascript"></script>
<script type="text/javascript">$(document).ready(function(){$('#loading', parent.document.body).css({display: 'none'})})</script>
<!--<script src="http://cdn.jquerytools.org/1.2.5/jquery.tools.min.js"></script>-->
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/Toolbar.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel.js" type="text/javascript"></script>
<!--<script src="--><?php //echo $this->baseUrl() ?><!--/js/lib/JsCalendar/driver.js" type="text/javascript"></script>-->
<script src="<?php echo $this->baseUrl() ?>/js/app/card/achievs/index/Card.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/app/card/achievs/index.js" type="text/javascript"></script>
</body>
</html>