<?php error_reporting(E_ALL ^ E_NOTICE) // отмена вывода замечаний notice?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/js/lib/Js/Toolbar/css/default.css');
		@import url('<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel/css/default.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/card/achievs/index.css');
	</style>
</head>
<body onload="init();">

	<form name="card" action="<?php echo $this->baseUrl() ?>/card/achievs/save" enctype="multipart/form-data" method="post">
		<fieldset>
			<input name="id" type="hidden" value="<?php echo $this->card->id ?>" />
			<input name="userId" type="hidden" value="<?php echo $this->user->getPersonId() ?>" />
			<input name="person_id" type="hidden" value="<?php echo $this->card->person_id ?>" />
			<input name="status_id" type="hidden" value="<?php echo $this->card->status_id ?>" />

			<input name="approvals[plan_mng_id]" type="hidden" value="<?php echo $this->card->plan_mng_id ?>" />
			<input name="approvals[plan_hmg_id]" type="hidden" value="<?php echo $this->card->plan_hmg_id ?>" />
			<input name="approvals[plan_fnc_id]" type="hidden" value="<?php echo $this->card->plan_fnc_id ?>" />

			<input name="approvals[plan_mng_status]" type="hidden" value="<?php echo $this->card->plan_mng_status ?>" />
			<input name="approvals[plan_emp_status]" type="hidden" value="<?php echo $this->card->plan_emp_status ?>" />
			<input name="approvals[plan_hmg_status]" type="hidden" value="<?php echo $this->card->plan_hmg_status ?>" />
			<input name="approvals[plan_fnc_status]" type="hidden" value="<?php echo $this->card->plan_fnc_status ?>" />

			<input name="approvals[rate_mng_id]" type="hidden" value="<?php echo $this->card->rate_mng_id ?>" />
			<input name="approvals[rate_hmg_id]" type="hidden" value="<?php echo $this->card->rate_hmg_id ?>" />
			<input name="approvals[rate_fnc_id]" type="hidden" value="<?php echo $this->card->rate_fnc_id ?>" />

			<input name="approvals[rate_mng_status]" type="hidden" value="<?php echo $this->card->rate_mng_status ?>" />
			<input name="approvals[rate_emp_status]" type="hidden" value="<?php echo $this->card->rate_emp_status ?>" />
			<input name="approvals[rate_hmg_status]" type="hidden" value="<?php echo $this->card->rate_hmg_status ?>" />
			<input name="approvals[rate_fnc_status]" type="hidden" value="<?php echo $this->card->rate_fnc_status ?>" />
			<input name="tab" type="hidden" value="<?php echo $this->tab?>" />

			<table class="panel">
				<tbody>
					<tr>
						<td class="panel-period">
							<div>
								Период:
								<?php echo $this->formSelect('period', $this->card->period, null, $this->periods) ?>
								<br><span class="translate_menu">Period:</span>
							</div>

						</td>
						<td class="panel-toolbar" id="toolbarBox"></td>
						<td class="panel-status">
							<div class="panel-status<?php echo $this->status->id ?>">
								<span title="Статус карточки"><?php echo $this->status->name ?></span>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
			<?php echo $this->achievsHeader($this->emp) ?>
			<div class="tabs">
				<table class="tabs-items">
					<tbody>
						<tr>
							<td id="tabs-item-tasks" class="tabs-item tabs-item-activated"><div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Бизнес-цели (<?php echo (count($this->tasks) - count($this->personalTasks)) ?>)</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 23px;">Business objectives</span></div></td>
							<td id="tabs-item-compets" class="tabs-item"><div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Компетенции (<?php echo count($this->active_competences) ?>)</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 164px;">Competences</span></div></td>
							<td id="tabs-item-trains" class="tabs-item"><div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">План развития (<?php echo count($this->trainings) ?>)</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 316px;">Development plan</span></div></td>
							<td id="tabs-item-comments" class="tabs-item"><div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Комментарии и согласования</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 470px;">Comments & approvals</span></div></td>
							<td id="tabs-item-personal" class="tabs-item"><div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Форма сотрудника</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 696px;">Personal form</span></div></td>
						</tr>
					</tbody>
				</table>
				<div class="tabs-body tabs-body-activated" id="tabs-body-tasks">
					<?php
						echo $this->achievsFormTasks($this->tasks, $this->count_func, $this->ratings, $this->rate_weights, $this->card->rtg_tasks_id, $this->userRole & $ROLE_FUNC_MANAGER, $this->card, $this->card->rtg_func_id)
					?>
				</div>
				<div class="tabs-body" id="tabs-body-compets">
					<?php echo $this->achievsFormCompetences($this->competences, $this->ratings, $this->rate_weights, $this->card->rtg_competens_id) ?>
				</div>
				<div class="tabs-body" id="tabs-body-trains">
					<?php echo $this->achievsFormTrainings($this->trainings,
							$this->trainsGroupsMethods, $this->trainsRespons, $this->months, $this->trainsGroupsMethodsActual) ?>
				</div>
				<div class="tabs-body" id="tabs-body-comments">
					<div class="comments-body">
						<div class="ratings-body">
							<table id="ratings" class="ratings-table">
								<tbody>
									<tr>
										<th>Итоговый рейтинг бизнес-целей:</th>
										<td><?php echo $this->ratings[$this->card->rtg_tasks_id] ?></td>
										<th>Итоговый рейтинг компетенций:</th>
										<td><?php echo $this->ratings[$this->card->rtg_competens_id] ?></td>
										<th class="ratings-field-total">Общий рейтинг:</th>
										<td id="fieldRatingTotal" class="field-rating ratings-field-total">
											<?php echo $this->formSelect('ratings[rtg_total_id]', $this->card->rtg_total_id, null, $this->ratings) ?>
											<div><?php echo $this->ratings[$this->card->rtg_total_id] ?></div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<table id="comments" class="grid-body-table comments-table">
							<tbody>
								<tr><th>Комментарий руководителя - <span class="translate_category_tasks">Manager's comment</span></th></tr>
								<tr>
									<td>
										<textarea name="comments[mng_comment]" readonly><?php echo $this->card->mng_comment ?></textarea>
									</td>
								</tr>


								<!--<tr><?php //if ($this->count_func > 0) echo '<th>Комментарий функционального руководителя - <span class="translate_category_tasks">Functional manager\'s comment</span></th>' ?></tr>
								<tr><?php /*if ($this->count_func > 0) echo '
									<td>
										<textarea name="comments[fnc_comment]" readonly>' . $this->card->fnc_comment . '</textarea>
									</td>'*/?>
								</tr>-->

								<tr><th>Рекомендации по развитию карьеры - <span class="translate_category_tasks">Career Development Recommendations</span></th></tr>
								<tr>
									<td class="comments-field-flags">
										<?php echo $this->achievsCareerFlags($this->card->career_flag_id, $this->careerFlags) ?>
									</td>
								</tr>
								<tr>
									<td>
										<textarea name="comments[career_recom]" readonly><?php echo $this->card->career_recom ?></textarea>
									</td>
								</tr>

								<tr><th>Карьерные ожидания сотрудника - <span class="translate_category_tasks">Employee’s Career Expectations</span></th></tr>
								<tr>
									<td>
										<textarea name="comments[career_wait]" readonly><?php echo $this->card->career_wait ?></textarea>
									</td>
								</tr>

								<!--<tr><th>Комментарий сотрудника - <span class="translate_category_tasks">Employee comment</span></th></tr>
								<tr>
									<td>
										<textarea name="comments123[emp_comment]" readonly><?php //echo $this->card->emp_comment ?></textarea>
									</td>
								</tr>-->
							</tbody>
						</table>
						<table class="approvals">
							<tbody>
								<tr>
									<td class="approvals-margin">&nbsp;</td>
									<td><?php echo $this->achievsTableApprovals($this->approvals, $this->card->status_id, $this->count_func) ?></td>
									<td class="approvals-margin">&nbsp;</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="tabs-body" id="tabs-body-personal">
					<?php echo $this->achievsFormPersonal(
						$this->tasks,
						$this->personalTrainings,
						$this->personalCompetences,
						$this->ratings,
						$this->rate_weights,
						$this->userRole & $ROLE_FUNC_MANAGER,
						$this->card,
						$this->status->id,
						// данные для компетенций
						$this->competences
						// $this->ratings, $this->rate_weights, $this->card->rtg_competens_id, TRUE
						);?>
				</div>

			</div>
		</fieldset>
	</form>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
<script type="text/javascript">
	$('#loading', parent.document.body).css({
			display: 'none'
	});
	$('#loading').css({
		display: 'block'
	});
</script>
<script type="text/javascript">
		var BASE_URL          = '<?php echo $this->baseUrl() ?>';

		/*function logoff()
		{

			var url = BASE_URL + '/default/logoff/index/';

	        if(!this.http){
	            this.http = new (window.XMLHttpRequest||ActiveXObject)("Msxml2.XMLHTTP");
	            this.working = false;
	        }
	        if (!this.working && this.http) {
	            this.http.open("GET", url, true);
	            this.working = true;
	            this.http.send(null);
	        }
		}*/

		var ROLE_VIEWER       = 0;
		var ROLE_EMPLOYEE     = 1;
		var ROLE_MANAGER      = 2;
		var ROLE_HIGH_MANAGER = 4;
		var ROLE_FUNC_MANAGER = 8;
		<?php $ROLE_FUNC_MANAGER = 8?>
		var USER_ROLE         = <?php echo $this->userRole ?>;
		var count_func 		  = <?php echo $this->count_func ?>;

		var emails = '<?php echo $this->emails ?>';
		//alert(mails);
		/*var dadat = '<?php //echo date() ?>';
		alert(dadat);*/

		var Str_Rate = '<?php
			$rat = array();
			$rates = $this->rate_name_weights;
			foreach ($rates as $key=>$value)
				$rat[] = $key;
			echo implode("," , $rat);
		?>';
		var Rate_Names = Str_Rate.split(",");

		var Str_Weight = '<?php
			$rat = array();
			$rates = $this->rate_name_weights;
			foreach ($rates as $key=>$value)
				$rat[] = $value[weight];
			echo implode("," , $rat);
		?>';
		var Rate_Weights = Str_Weight.split(",");

		var active_tab = '<?php echo $this->tab?>';

	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/Js.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/Toolbar.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/JsCalendar/driver.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/app/card/achievs/index/Card.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/app/card/achievs/index.js" type="text/javascript"></script>
</body>
</html>