<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/js/lib/Js/Toolbar/css/default.css" />-->
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/js/lib/Js/Tree/css/default.css" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/css/app/logo.css" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/default/index/index.css" />
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/css/app/default/integrated/index.css" />-->
<!--	<link rel="stylesheet" type="text/css" href="--><?php //echo $this->baseUrl() ?><!--/css/app/default/index/index/menu.css" />-->
	<script src="<?php echo $this->baseUrl() ?>/js/iepngfix_tilebg.js" type="text/javascript"></script>
</head>
<body onload="init()" >
<div id="integrated_block"><?php echo $this->integratedBlock() ?></div>

	<div class="logo"><div class="integrate_name"><?php echo $this->is_integrate ?></div></div>
	<div id="_ajax"></div>
	<div id="toolbar" style="display: block;"></div>
	<div id="sidebar" style="display: block;">
		<div class="caption"><div>Личные папки - Personal folders</div></div>
		<div id="menu"></div>
	</div>
	<div id="delimiter" class="delimiter" style="display: block;"></div>
	<div id="container" style="display: block;">
		<div class="caption"><div id="captionLabel"></div></div>
		<iframe id="content" name="content" type="text/html" data="<?php echo $this->baseUrl() ?>/empty"></iframe>
	</div>

<div id="loading">
	<div id="overlay"></div>
	<div id="text">
		<div id="alert">Загрузка...<span>Loading...</span></div>
		<div id="image"><img height="32px" width="32px" src="/img/loading.gif" alt="Загрузка..." /></div>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function(){$('#loading', parent.document.body).css({display: 'none'})})
	$('#loading').css({display: 'block'});
</script>
<script type="text/javascript">
	var BASE_URL = '<?php echo $this->baseUrl() ?>';
	var have_integrate = <?php echo $this->have_integrate ?>;
</script>
<script src="<?php echo $this->baseUrl() ?>/json/user" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/Toolbar.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/Tree.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/JsDataLoader.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/app/default/index/index/Main.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/app/default/index/index.js" type="text/javascript"></script>
</body>
</html>