<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/card/achievs-task-notes/index.css" />
</head>
<body>

<div class="addHyperlink_div" id="hyperlink_div" style="display: none;">
	<span class='caption_hyperlink'>Выберите файл:</span>
	<input type="file" name="hyperlink_file" value="" onchange="copyPath(this.value)">
	<br>
	<span class='caption_hyperlink'>Для добавления ссылки нажмите кнопку:</span>
	<input type="text" id="addHyperlink_input" class="addHyperlink_text" />
	<input type="button" value="Добавить" onclick="getHyperlink()" />
</div>

	<form name="taskNotes" action="<?php echo $this->baseUrl() ?>/card/achievs-task-notes/save" enctype="multipart/form-data" method="post">
		<fieldset>
			<input name="task[id]" type="hidden" value="<?php echo $this->task->id ?>" />
			<input name="is_personal" type="hidden" value="<?php echo $this->is_personal ?>" />
			<div class="task">
				<div class="task-label">Бизнес-цель</div>
				<div class="task-description"><?php echo nl2br($this->task->description) ?></div>
			</div>
			<div class="notes">
				<?php echo $this->achievsTaskNotes($this->notes, $this->is_personal) ?>
			</div>
			<div class="newnote">
				<div class="newnote-label">Новая заметка &nbsp;&nbsp;<img alt="Добавить ссылку" src="<?php echo $this->baseUrl() ?>/img/achievs/card/hyperlink.bmp" onclick="AddHyperlink(event.clientX + document.documentElement.scrollLeft, event.clientY + document.documentElement.scrollTop);" style="cursor: hand;"></div>
				<div class="newnote-field-text"><textarea name='newNote[text]' ></textarea></div>
				<div class="newnote-submit"><input name="submit" type="submit" value="Сохранить" /></div>
			</div>
		</fieldset>
	</form>
<script type="text/javascript">
	var BASE_URL = '<?php echo $this->baseUrl() ?>';


	function AddHyperlink(posX, posY)
	{
		var tip = document.getElementById('hyperlink_div');

		tip.style.left = posX - 100;
		tip.style.top = posY - 30;

		if (tip.style.display == "none")
			tip.style.display = "block";
	}

	function copyPath(data)
	{
		var input = document.getElementById('addHyperlink_input');
		input.value = data;

	}

	function getHyperlink()
	{
		var input = document.getElementById('addHyperlink_input');
		var text = input.value;

		var hyperlink = "<a href='" + text + "' target='_blank'>ссылка</a>";

		var textarea = document.getElementById('newNote[text]');

		if (text.length > 0)
			textarea.value = textarea.value + hyperlink;

		input.value = "";

		var tip = document.getElementById('hyperlink_div');
		tip.style.display = "none";

	}
</script>
</body>
</html>