<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/lib/GridBox/gridbox.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/default/profile/trainings.css');
	</style>
</head>
<body>
	<?php echo $this->profileTrainings($this->trainings, $this->groupsMethods, $this->respons, $this->months) ?>
</body>
</html>