<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/card/personal/index.css');
	</style>
</head>
<body>
	<table>
		<tbody>
			<tr>
				<th>Сотрудник<br>Employee</th>
				<td>
					<?php echo $this->personal->fullname ?>
					<!--<span class="redundant"><?php echo $this->personal->redundant ?></span>-->
				
				</td>
			</tr>
			<tr>
				<th>Дата рождения<br>Date of birth</th>
				<td><?php echo $this->personal->date_birth ?></td>
			</tr>
			<tr>
				<th>Компания<br>Company</th>
				<td><?php echo $this->personal->company ?></td>
			</tr>
			<tr>
				<th>Отдел<br>Department</th>
				<td><?php echo $this->personal->department ?></td>
			</tr>
			<tr>
				<th>Должность<br>Post</th>
				<td><?php echo $this->personal->appointment ?></td>
			</tr>
			<tr>
				<th>Грейд<br>Grade</th>
				<td><?php echo $this->personal->grade ?></td>
			</tr>
			<tr>
				<th>Бизнес-юнит<br>Business unit</th>
				<td><?php echo $this->personal->business_unit ?></td>
			</tr>
			<tr>
				<th>Семейство должностей<br>Job family</th>
				<td><?php echo $this->personal->job_family ?></td>
			</tr>
		</tbody>
	</table>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
<script type="text/javascript">
	$('#loading', parent.document.body).css({
			display: 'none'
	});
</script>
</body>
</html>