<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/card/index/create.css');
	</style>
</head>
<body>
	<div id="cardCreate">
		<form name="cardCreate" action="<?php echo $this->baseUrl() ?>/card/card/create" method="post">
			<fieldset>
				<legend>Создание новой карты</legend>
				<input name="person_id" type="hidden" value="<?php echo $this->person_id ?>" />
				<input name="card_creator_id" type="hidden" value="<?php echo $this->user->person_id ?>" />
				<div class="form-item">
					<?php echo $this->formLabel('period_start', 'Период начала действия новой карты')?>
					<?php echo $this->formText('period_start', date('d.m.Y'))?>
				</div>
			</fieldset>
			<?php echo $this->formSubmit(NULL, 'Создать карту')?>
		</form>
	</div>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
<script type="text/javascript">

	var BASE_URL  = '<?php echo $this->baseUrl() ?>';
	var person_fio = '<?php echo $this->person->surname?> <?php echo mb_substr($this->person->name, 0, 1)?>.<?php echo mb_substr($this->person->patronymic, 0, 1)?>.';

	$(document).ready(function(){
		$('input[type=submit]').click(function(){
			var answer = confirm('Создать для сотрудника '+person_fio+' карту на период c '+$('#period_start').val()+'?');
			if (! answer)
				return false;
		})
	})
</script>
</body>
</html>