<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/card/index/create.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/lib/jquery-ui-1.8.16.custom.css" />
</head>
<body>
	<div id="cardCreate">
		<form name="cardCreate" action="<?php echo $this->baseUrl() ?>/card/card/create" method="post">
			<fieldset>
				<legend>Создание новой карты</legend>
				<input name="person_id" type="hidden" value="<?php echo $this->person_id ?>" />
				<input name="card_creator_id" type="hidden" value="<?php echo $this->user->person_id ?>" />
				<div class="form-item">
					<?php echo $this->formLabel('period_start', 'Период начала действия новой карты')?>
					<?php echo $this->formText('period_start', date('d.m.Y'))?>
				</div>
			</fieldset>
			<?php echo $this->formSubmit(NULL, 'Создать карту')?>
		</form>
	</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.ui.datepicker-ru.js" type="text/javascript"></script>
<script type="text/javascript">
	var BASE_URL  = '<?php echo $this->baseUrl() ?>';
	var person_fio = '<?php echo $this->person->surname?> <?php echo mb_substr($this->person->name, 0, 1)?>.<?php echo mb_substr($this->person->patronymic, 0, 1)?>.';

	$(document).ready(function(){
		$('input[type=submit]').click(function(){
			var answer = confirm('Создать для сотрудника '+person_fio+' карту на период c '+$('#period_start').val()+'?');
			if (! answer)
				return false;
		})
		$('#period_start').datepicker({
			dateFormat: 'dd.mm.yy',
			changeMonth: true,
			showButtonPanel: true,
			beforeShow: function(input,inst){
				inst.dpDiv.css(
					{
						'top': 0,
						'right': 0
					}
				);
			}
		});
	})
</script>
</body>
</html>