<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel/css/default.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/card/index/index.css');
	</style>
	<script type="text/javascript">
		
		var BASE_URL  = '<?php echo $this->baseUrl() ?>';
		
	</script>
</head>
<body onload="init()" >
	<div class="tabs">
		<table class="tabs-items">
			<tbody>
				<tr>
					<td id="tabs-item-achievs" class="tabs-item tabs-item-activated">
						<div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Управление Достижениями</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 24px;">Achievments management</span></div>
					</td>
					<td id="tabs-item-personal" class="tabs-item">
						<div><span style="font-weight: bold; font-size:11px; height: 10px; position: relative; top: -8px; ">Персональная информация</span><span style="color: #888888; font-size:10px; height: 10px; position: absolute; top: 8px; left: 218px; ">Personal data</span></div>
					</td>
				</tr>
			</tbody>
		</table>
		<div id="tabs-body-achievs" class="tabs-body tabs-body-activated">
			<iframe name="achievs" src="<?php echo $this->baseUrl() ?>/card/achievs/index/personid/<?php echo $this->person->id ?>"></iframe>
		</div>
		<div id="tabs-body-personal" class="tabs-body">
			<iframe name="personal" src="<?php echo $this->baseUrl() ?>/card/personal/index/personid/<?php echo $this->person->id ?>"></iframe>
		</div>
	</div>
	<div id="loading">
		<div id="text">
			<div id="alert">Загрузка...<span>Loading...</span></div>
			<div id="image"><img src="/img/loading.gif"></div>
		</div>
	</div>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
	<script type="text/javascript">
		$('#loading', parent.document.body).css({
				display: 'none'
		});
		$('#loading').css({
			display: 'block'
		});
	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/Js.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/lib/Js/TabPanel.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/app/card/index/index.js" type="text/javascript"></script>
</body>
</html>