<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/index.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/app/default/error/error.css" />
</head>
<body>
<div class="caption"><?php echo $this->escape($this->caption) ?></div>
<div class="message"><?php echo $this->escape($this->message) ?></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">$(document).ready(function(){$('#loading', parent.document.body).css({display: 'none'})});</script>
</body>
</html>