<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->escape($this->title) ?></title>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<style type="text/css">
		@import url('<?php echo $this->baseUrl() ?>/css/app/index.css');
		@import url('<?php echo $this->baseUrl() ?>/css/app/default/error/error.css');
	</style>
</head>
<body>
	<div class="caption"><?php echo $this->escape($this->caption) ?></div>
	<div class="message"><?php echo $this->escape($this->message) ?></div>
<script src="<?php echo $this->baseUrl() ?>/js/lib/jquery.1.4.4.js" type="text/javascript"></script>
<script type="text/javascript">
	$('#loading', parent.document.body).css({
			display: 'none'
	});
</script>
</body>
</html>